### ISSUE TITLE
How can we test-packages in a CI with chromedriver ?

### ISSUE THREAD

**Issue by theodorDiaconu** [meteortesting/meteor-mocha#48]
```
sudo: false
addons:
  chrome: stable
language: node_js
node_js:
  - "8.9.1"
before_install:
  - curl https://install.meteor.com/?release=1.6 | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - meteor npm i --save-dev selenium-webdriver chromedriver
script:
  - TEST_BROWSER_DRIVER=chrome meteor --once test-packages --driver-package meteortesting:mocha ./
```

Output:
```
I20171126-23:47:34.314(0)? --------------------------------
I20171126-23:47:34.314(0)? ----- RUNNING CLIENT TESTS -----
I20171126-23:47:34.314(0)? --------------------------------
W20171126-23:47:34.337(0)? (STDERR) { Error: Cannot find module 'chromedriver'
W20171126-23:47:34.337(0)? (STDERR)     at Function.Module._resolveFilename (module.js:513:15)
W20171126-23:47:34.338(0)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20171126-23:47:34.338(0)? (STDERR)     at Object.require (/tmp/meteor-test-run1nqoqn7.xewu/.meteor/local/build/programs/server/boot.js:287:32)
W20171126-23:47:34.338(0)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:641:18)
W20171126-23:47:34.338(0)? (STDERR)     at require (packages/modules-runtime.js:234:16)
W20171126-23:47:34.339(0)? (STDERR)     at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:29:5)
W20171126-23:47:34.339(0)? (STDERR)     at startBrowser (packages/meteortesting:browser-tests/server.js:22:7)
W20171126-23:47:34.339(0)? (STDERR)     at clientTests (packages/meteortesting:mocha/server.js:119:3)
W20171126-23:47:34.339(0)? (STDERR)     at serverTests (packages/meteortesting:mocha/server.js:144:7)
W20171126-23:47:34.339(0)? (STDERR)     at mochaInstance.run.failureCount (packages/meteortesting:mocha/server.js:99:13) code: 'MODULE_NOT_FOUND' }
```

Any ideas, work arounds ? Thank you!

**Comment by theodorDiaconu** [comment]
Hackish but it works!

```
sudo: false

addons:
  chrome: stable

language: node_js

node_js:
  - "8.9.1"

before_install:
  - curl https://install.meteor.com/?release=1.6 | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"

cache:
  directories:
    - ~/.npm
    - "node_modules"

notifications:
  email: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - meteor create --bare test
  - cd test
  - meteor npm i --save selenium-webdriver chromedriver
  - METEOR_PACKAGE_DIRS="../" TEST_BROWSER_DRIVER=chrome meteor --once test-packages --driver-package meteortesting:mocha ../
```
